apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ofri-test
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "ofri-test"
        objectType: "secretsmanager"
      - objectName: "ofri-jenkins"
        objectType: "ssmparameter"