apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ofri-test
  name: jenkins-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["pods", "pods/log", "services", "deployments", "jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]