apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployment-binding
  namespace: ofri-pollyapp
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: ofri-test
roleRef:
  kind: Role
  name: jenkins-deployment-manager
  apiGroup: rbac.authorization.k8s.io