name: my-python-app
namespace: ofri-test
replicaCount: 2

image:
  repository: 023196572641.dkr.ecr.us-east-2.amazonaws.com/libermanofri/app-repo
  tag: "app-image-0.3.${BUILD_NUMBER}"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

pvc:
  storage: 1Gi
ingress:
  host: nginx.local

env:
  TELEGRAM_TOKEN_SECRET: telegram-token-secret

imagePullSecrets:
  - name: ecr-registry-secret

secretProviderClass:
  enabled: true
  name: jenkins-secret-provider  # Specify the SecretProviderClass name created earlier

extraVolumes:
  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: jenkins-secret-provider

extraVolumeMounts:
  - name: secrets-store
    mountPath: /mnt/secrets  # Adjust as necessary
    readOnly: true
